package com.c1b1.v2.studyone.studyone;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/v1/words") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called dailyWordRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DailyWordRepository dailyWords;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String add (@RequestParam String word
            , @RequestParam String meaning) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        DailyWord w = new DailyWord();
        w.setWord(word);
        w.setMeaning(meaning);
        dailyWords.save(w);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<DailyWord> getAllWords() {
        // This returns a JSON or XML with the words
        return dailyWords.findAll();
    }
}